version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_USER=SA
      - MSSQL_SA_PASSWORD=p4ssw0rd!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - ./bak/:/mssql/backup/         # 備份檔案目錄
      - ./data/:/var/opt/mssql/data/    # MDF 與 LDF 檔案目錄

  attach:
    image: mcr.microsoft.com/mssql-tools:latest
    platform: linux/amd64
    depends_on:
      - mssql
    volumes:
      - ./data/:/var/opt/mssql/data/
      - ./scripts/:/scripts/
    entrypoint: ["/bin/bash", "/scripts/attach_databases.sh"]

  adminer:
    image: adminer
    restart: always
    depends_on:
      - mssql
    ports:
      - 8080:8080
